sudo: required
language: node_js
node_js:
  - "8.15.1"
services: 
  - docker

before_install: 
  - docker build -t pavanpagan/react-test -f ./client/Dockerfile.dev ./client

script:
  - echo "script start"


after_success:
  - docker build -t pavanpagan/multi-client ./client
  - docker build -t pavanpagan/multi-nginx ./nginx
  - docker build -t pavanpagan/multi-server ./server
  - docker build -t pavanpagan/multi-worker ./worker
  # log into docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push to docker hub
  - docker push pavanpagan/multi-nginx
  - docker push pavanpagan/multi-server
  - docker push pavanpagan/multi-worker
  - docker push pavanpagan/multi-client
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-423694414493
  bucket_path: docker_multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  



